# Generated by Django 6.0 on 2025-12-30 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='content',
        ),
        migrations.RemoveField(
            model_name='report',
            name='title',
        ),
        migrations.AddField(
            model_name='report',
            name='account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='annual_bill_report',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='annual_service_reports',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='credit_limit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='foundation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='monthly_bill_report',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='monthly_service_reports',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='notifications_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='service_details',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='service_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='service_recipient_at_branch',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='usage_details',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='user_biometric',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['account_number'], name='reports_rep_account_4b3cc0_idx'),
        ),
    ]
